package io.bio4j.kafkarpc.protoc;

import com.google.protobuf.compiler.PluginProtos;
import com.google.protobuf.DescriptorProtos;

import java.util.*;

/**
 * Protoc plugin that generates Kafka RPC stubs and service base from .proto service definitions.
 */
public class KafkaRpcGenerator {

    public static void main(String[] args) throws Exception {
        var request = PluginProtos.CodeGeneratorRequest.parseFrom(System.in);
        var response = generate(request);
        response.writeTo(System.out);
    }

    static PluginProtos.CodeGeneratorResponse generate(PluginProtos.CodeGeneratorRequest request) {
        var builder = PluginProtos.CodeGeneratorResponse.newBuilder();
        Map<String, String> packageByFile = new HashMap<>();

        for (DescriptorProtos.FileDescriptorProto file : request.getProtoFileList()) {
            String pkg = file.getPackage().isEmpty() ? "" : file.getPackage() + ".";
            for (var dep : file.getDependencyList()) {
                packageByFile.put(dep, packageByFile.getOrDefault(dep, ""));
            }
            packageByFile.put(file.getName(), pkg);
        }

        for (String name : request.getFileToGenerateList()) {
            DescriptorProtos.FileDescriptorProto file = null;
            for (DescriptorProtos.FileDescriptorProto f : request.getProtoFileList()) {
                if (f.getName().equals(name)) {
                    file = f;
                    break;
                }
            }
            if (file == null) continue;

            String javaPackage = file.getOptions().getJavaPackage();
            if (javaPackage.isEmpty()) {
                javaPackage = toJavaPackage(file.getPackage());
            }
            String outPkg = javaPackage;

            for (DescriptorProtos.ServiceDescriptorProto service : file.getServiceList()) {
                String className = service.getName() + "KafkaRpc";
                String fullName = outPkg + "." + className;
                String content = generateService(file, service, outPkg, javaPackage);
                builder.addFile(PluginProtos.CodeGeneratorResponse.File.newBuilder()
                    .setName(javaPackage.replace('.', '/') + "/" + className + ".java")
                    .setContent(content)
                    .build());
            }
        }
        return builder.build();
    }

    private static String toJavaPackage(String protoPackage) {
        if (protoPackage.isEmpty()) return "";
        return protoPackage.replace('.', '_');
    }

    private static String generateService(DescriptorProtos.FileDescriptorProto file,
                                         DescriptorProtos.ServiceDescriptorProto service,
                                         String outPkg, String javaPackage) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by kafka-rpc-protoc. Do not edit.\n");
        sb.append("package ").append(outPkg).append(";\n\n");
        sb.append("import com.google.protobuf.InvalidProtocolBufferException;\n");
        sb.append("import java.io.IOException;\n");
        sb.append("import io.bio4j.kafkarpc.KafkaRpcChannel;\n");
        sb.append("import io.bio4j.kafkarpc.KafkaRpcConstants;\n");
        sb.append("import io.bio4j.kafkarpc.KafkaRpcServer;\n");
        sb.append("import io.bio4j.kafkarpc.KafkaRpcService;\n");
        sb.append("import java.util.Map;\n");
        sb.append("import java.util.Properties;\n");
        sb.append("import java.util.UUID;\n");
        sb.append("import java.util.HashMap;\n\n");
        sb.append("/** Client stub for ").append(service.getName()).append(" service over Kafka. */\n");
        sb.append("public final class ").append(service.getName()).append("KafkaRpc {\n\n");
        sb.append("  public static final String SERVICE_NAME = \"").append(service.getName()).append("\";\n\n");
        sb.append("  private ").append(service.getName()).append("KafkaRpc() {}\n\n");

        // Stub
        sb.append("  /** Blocking stub. */\n");
        sb.append("  public static final class Stub {\n");
        sb.append("    private final KafkaRpcChannel channel;\n");
        sb.append("    private final String requestTopic;\n");
        sb.append("    private final String replyTopic;\n\n");
        sb.append("    public Stub(KafkaRpcChannel channel, String requestTopic, String replyTopic) {\n");
        sb.append("      this.channel = channel;\n");
        sb.append("      this.requestTopic = requestTopic;\n");
        sb.append("      this.replyTopic = replyTopic;\n");
        sb.append("    }\n\n");

        for (DescriptorProtos.MethodDescriptorProto method : service.getMethodList()) {
            String inputType = resolveType(method.getInputType(), file, javaPackage);
            String outputType = resolveType(method.getOutputType(), file, javaPackage);
            String methodName = lowerFirst(method.getName());
            String fullMethod = service.getName() + "/" + method.getName();
            sb.append("    public ").append(outputType).append(" ").append(methodName)
              .append("(").append(inputType).append(" request) throws IOException, InvalidProtocolBufferException, java.util.concurrent.TimeoutException {\n");
            sb.append("      String correlationId = UUID.randomUUID().toString();\n");
            sb.append("      Map<String, String> headers = new HashMap<>();\n");
            sb.append("      headers.put(KafkaRpcConstants.HEADER_METHOD, \"").append(fullMethod).append("\");\n");
            sb.append("      byte[] response = channel.request(correlationId, request.toByteArray(), headers);\n");
            sb.append("      return ").append(outputType).append(".parseFrom(response);\n");
            sb.append("    }\n\n");
        }
        sb.append("  }\n\n");

        // ServiceBase
        sb.append("  /** Server base - extend and override methods. Implements KafkaRpcService for Spring. */\n");
        sb.append("  public abstract static class ServiceBase implements KafkaRpcService {\n");
        sb.append("    public abstract String getRequestTopic();\n");
        sb.append("    public abstract String getReplyTopic();\n\n");
        sb.append("    public Map<String, KafkaRpcServer.MethodHandler> getHandlers() {\n");
        sb.append("      Map<String, KafkaRpcServer.MethodHandler> m = new HashMap<>();\n");
        for (DescriptorProtos.MethodDescriptorProto method : service.getMethodList()) {
            String fullMethod = service.getName() + "/" + method.getName();
            sb.append("      m.put(\"").append(fullMethod).append("\", getHandler(\"").append(fullMethod).append("\"));\n");
        }
        sb.append("      return m;\n");
        sb.append("    }\n\n");
        sb.append("    public KafkaRpcServer.MethodHandler getHandler(String method) {\n");
        sb.append("      return (correlationId, request) -> {\n");
        sb.append("        switch (method) {\n");
        for (DescriptorProtos.MethodDescriptorProto method : service.getMethodList()) {
            String inputType = resolveType(method.getInputType(), file, javaPackage);
            String outputType = resolveType(method.getOutputType(), file, javaPackage);
            String methodName = lowerFirst(method.getName());
            String fullMethod = service.getName() + "/" + method.getName();
            sb.append("          case \"").append(fullMethod).append("\" -> {\n");
            sb.append("            ").append(inputType).append(" req;\n");
            sb.append("            try { req = ").append(inputType).append(".parseFrom(request); }\n");
            sb.append("            catch (InvalidProtocolBufferException e) { throw new RuntimeException(e); }\n");
            sb.append("            return ").append(methodName).append("(req).toByteArray();\n");
            sb.append("          }\n");
        }
        sb.append("          default -> throw new IllegalArgumentException(\"Unknown method: \" + method);\n");
        sb.append("        }\n");
        sb.append("      };\n");
        sb.append("    }\n\n");
        for (DescriptorProtos.MethodDescriptorProto method : service.getMethodList()) {
            String inputType = resolveType(method.getInputType(), file, javaPackage);
            String outputType = resolveType(method.getOutputType(), file, javaPackage);
            sb.append("    protected abstract ").append(outputType).append(" ")
              .append(lowerFirst(method.getName())).append("(").append(inputType).append(" request);\n");
        }
        sb.append("  }\n");
        sb.append("}\n");
        return sb.toString();
    }

    private static String resolveType(String protoType, DescriptorProtos.FileDescriptorProto file, String javaPackage) {
        if (protoType.startsWith(".")) {
            protoType = protoType.substring(1);
        }
        String shortName = protoType.contains(".") ? protoType.substring(protoType.lastIndexOf('.') + 1) : protoType;
        String protoPkg = file.getPackage();
        if (protoType.startsWith(protoPkg) || (protoPkg.isEmpty() && !protoType.contains("."))) {
            return javaPackage + "." + shortName;
        }
        if (protoType.contains(".")) {
            String pkg = protoType.substring(0, protoType.lastIndexOf('.'));
            return pkg.replace('.', '_') + "." + shortName;
        }
        return javaPackage + "." + shortName;
    }

    private static String lowerFirst(String s) {
        return Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }
}