package io.bio4j.kafkarpc.protoc;

import com.google.protobuf.DescriptorProtos.*;
import com.google.protobuf.compiler.PluginProtos;

import java.util.*;

/**
 * protoc plugin that generates Kafka RPC client stubs and server base classes from .proto service definitions.
 * Generates only unary RPC methods (no streaming).
 */
public class KafkaRpcGenerator {

    public static void main(String[] args) throws Exception {
        PluginProtos.CodeGeneratorRequest request = PluginProtos.CodeGeneratorRequest.parseFrom(System.in);
        PluginProtos.CodeGeneratorResponse response = generate(request);
        response.writeTo(System.out);
    }

    static PluginProtos.CodeGeneratorResponse generate(PluginProtos.CodeGeneratorRequest request) {
        var responseBuilder = PluginProtos.CodeGeneratorResponse.newBuilder();

        // Build type name -> file index for resolving cross-file types
        Map<String, FileDescriptorProto> typeToFile = new HashMap<>();
        for (FileDescriptorProto file : request.getProtoFileList()) {
            String pkg = file.getPackage();
            String prefix = pkg.isEmpty() ? "" : "." + pkg + ".";
            for (DescriptorProto msg : file.getMessageTypeList()) {
                typeToFile.put(prefix + msg.getName(), file);
            }
        }

        Set<String> toGenerate = new HashSet<>(request.getFileToGenerateList());
        Map<String, FileDescriptorProto> protoFiles = new HashMap<>();
        for (FileDescriptorProto f : request.getProtoFileList()) {
            protoFiles.put(f.getName(), f);
        }

        for (String fileName : toGenerate) {
            FileDescriptorProto file = protoFiles.get(fileName);
            if (file == null) continue;

            for (ServiceDescriptorProto service : file.getServiceList()) {
                if (service.getMethodCount() == 0) continue;

                // Only unary methods
                var unaryMethods = service.getMethodList().stream()
                        .filter(m -> !m.getClientStreaming() && !m.getServerStreaming())
                        .toList();
                if (unaryMethods.isEmpty()) continue;

                String javaPackage = file.getOptions().hasJavaPackage()
                        ? file.getOptions().getJavaPackage()
                        : file.getPackage().replace(".", "");
                String serviceName = service.getName();
                String className = serviceName + "KafkaRpc";
                String fullClassName = javaPackage + "." + className;
                String path = javaPackage.replace(".", "/") + "/" + className + ".java";

                String content = generateServiceClass(file, service, unaryMethods, javaPackage, typeToFile);
                responseBuilder.addFile(
                        PluginProtos.CodeGeneratorResponse.File.newBuilder()
                                .setName(path)
                                .setContent(content)
                                .build());
            }
        }

        return responseBuilder.build();
    }

    private static String generateServiceClass(FileDescriptorProto file, ServiceDescriptorProto service,
                                               List<MethodDescriptorProto> methods,
                                               String javaPackage,
                                               Map<String, FileDescriptorProto> typeToFile) {
        String serviceName = service.getName();
        var sb = new StringBuilder();

        sb.append("// Generated by kafka-rpc-protoc. Do not edit.\n");
        sb.append("package ").append(javaPackage).append(";\n\n");
        sb.append("import com.google.protobuf.InvalidProtocolBufferException;\n");
        sb.append("import java.io.IOException;\n");
        sb.append("import io.bio4j.kafkarpc.KafkaRpcChannel;\n");
        sb.append("import io.bio4j.kafkarpc.KafkaRpcConstants;\n");
        sb.append("import io.bio4j.kafkarpc.KafkaRpcServer;\n");
        sb.append("import java.util.Map;\n");
        sb.append("import java.util.Properties;\n");
        sb.append("import java.util.UUID;\n");
        sb.append("import java.util.HashMap;\n\n");

        // Stub (client)
        sb.append("/** Client stub for ").append(serviceName).append(" service over Kafka. */\n");
        sb.append("public final class ").append(serviceName).append("KafkaRpc {\n\n");

        sb.append("  public static final String SERVICE_NAME = \"").append(serviceName).append("\";\n\n");

        sb.append("  private ").append(serviceName).append("KafkaRpc() {}\n\n");

        sb.append("  /** Blocking stub. */\n");
        sb.append("  public static final class Stub {\n");
        sb.append("    private final KafkaRpcChannel channel;\n");
        sb.append("    private final String requestTopic;\n");
        sb.append("    private final String replyTopic;\n\n");
        sb.append("    public Stub(KafkaRpcChannel channel, String requestTopic, String replyTopic) {\n");
        sb.append("      this.channel = channel;\n");
        sb.append("      this.requestTopic = requestTopic;\n");
        sb.append("      this.replyTopic = replyTopic;\n");
        sb.append("    }\n\n");

        for (MethodDescriptorProto method : methods) {
            String methodName = camelCase(method.getName());
            String inputType = toJavaType(method.getInputType(), file, javaPackage, typeToFile);
            String outputType = toJavaType(method.getOutputType(), file, javaPackage, typeToFile);
            String fullMethodName = serviceName + "/" + method.getName();

            sb.append("    public ").append(outputType).append(" ").append(methodName).append("(")
                    .append(inputType).append(" request) throws IOException, InvalidProtocolBufferException, java.util.concurrent.TimeoutException {\n");
            sb.append("      String correlationId = UUID.randomUUID().toString();\n");
            sb.append("      Map<String, String> headers = new HashMap<>();\n");
            sb.append("      headers.put(KafkaRpcConstants.HEADER_METHOD, \"").append(fullMethodName).append("\");\n");
            sb.append("      byte[] response = channel.request(correlationId, request.toByteArray(), headers);\n");
            sb.append("      return ").append(outputType).append(".parseFrom(response);\n");
            sb.append("    }\n\n");
        }

        sb.append("  }\n\n");

        // Service base (server) - abstract class to extend
        sb.append("  /** Server base - extend and override methods. */\n");
        sb.append("  public abstract static class ServiceBase {\n");
        sb.append("    public abstract String getRequestTopic();\n");
        sb.append("    public abstract String getReplyTopic();\n\n");
        sb.append("    public Map<String, KafkaRpcServer.MethodHandler> getHandlers() {\n");
        sb.append("      Map<String, KafkaRpcServer.MethodHandler> m = new HashMap<>();\n");
        for (MethodDescriptorProto method : methods) {
            String fullMethodName = serviceName + "/" + method.getName();
            sb.append("      m.put(\"").append(fullMethodName).append("\", getHandler(\"").append(fullMethodName).append("\"));\n");
        }
        sb.append("      return m;\n");
        sb.append("    }\n\n");
        sb.append("    public KafkaRpcServer.MethodHandler getHandler(String method) {\n");
        sb.append("      return (correlationId, request) -> {\n");
        sb.append("        switch (method) {\n");

        for (MethodDescriptorProto method : methods) {
            String methodName = camelCase(method.getName());
            String inputType = toJavaType(method.getInputType(), file, javaPackage, typeToFile);
            String outputType = toJavaType(method.getOutputType(), file, javaPackage, typeToFile);
            String fullMethodName = serviceName + "/" + method.getName();

            sb.append("          case \"").append(fullMethodName).append("\" -> {\n");
            sb.append("            ").append(inputType).append(" req;\n");
            sb.append("            try { req = ").append(inputType).append(".parseFrom(request); }\n");
            sb.append("            catch (InvalidProtocolBufferException e) { throw new RuntimeException(e); }\n");
            sb.append("            return ").append(methodName).append("(req).toByteArray();\n");
            sb.append("          }\n");
        }

        sb.append("          default -> throw new IllegalArgumentException(\"Unknown method: \" + method);\n");
        sb.append("        }\n");
        sb.append("      };\n");
        sb.append("    }\n\n");

        for (MethodDescriptorProto method : methods) {
            String methodName = camelCase(method.getName());
            String inputType = toJavaType(method.getInputType(), file, javaPackage, typeToFile);
            String outputType = toJavaType(method.getOutputType(), file, javaPackage, typeToFile);
            sb.append("    protected abstract ").append(outputType).append(" ").append(methodName)
                    .append("(").append(inputType).append(" request);\n");
        }

        sb.append("  }\n");
        sb.append("}\n");

        return sb.toString();
    }

    private static String toJavaType(String protoType, FileDescriptorProto currentFile,
                                     String currentPackage, Map<String, FileDescriptorProto> typeToFile) {
        if (protoType.startsWith(".")) protoType = protoType.substring(1);
        String simpleName = protoType.contains(".") ? protoType.substring(protoType.lastIndexOf('.') + 1) : protoType;

        FileDescriptorProto definingFile = typeToFile.get("." + protoType);
        if (definingFile == null) {
            definingFile = typeToFile.get(protoType);
        }
        if (definingFile != null && definingFile.equals(currentFile)) {
            return simpleName;
        }
        String javaPkg = definingFile != null && definingFile.getOptions().hasJavaPackage()
                ? definingFile.getOptions().getJavaPackage()
                : (definingFile != null ? definingFile.getPackage().replace(".", "") : currentPackage);
        return javaPkg + "." + simpleName;
    }

    private static String camelCase(String name) {
        if (name == null || name.isEmpty()) return name;
        return name.substring(0, 1).toLowerCase() + name.substring(1);
    }
}
